backgrounds = [
    "Dungeon Master's Guide",
    "Player's Handbook",
    "Sword Coast Adventurer's Guide",
    "Tasha's Cauldron of Everything",
    "Waterdeep: Dragon Heist",
    "Xanathar's Guide to Everything",
]

feats = [
    "Dungeon Master's Guide",
    "Fizban's Treasury of Dragons",
    "Monster Manual",
    "Mordenkainen Presents: Monsters of the Multiverse",
    "Player's Handbook",
    "Sword Coast Adventurer's Guide",
    "Tasha's Cauldron of Everything",
    "Xanathar's Guide to Everything",
]

features = [
    "Dungeon Master's Guide",
    "Fizban's Treasury of Dragons",
    "Player's Handbook",
    "Sword Coast Adventurer's Guide",
    "Tasha's Cauldron of Everything",
    "Xanathar's Guide to Everything",
]

items = [
    "Dungeon Master's Guide",
    "Player's Handbook",
    "Sword Coast Adventurer's Guide",
    "Tasha's Cauldron of Everything",
    "Waterdeep: Dragon Heist",
    "Waterdeep: Dungeon of the Mad Mage",
    "Xanathar's Guide to Everything",
]

monsters = [
    "Dungeon Master's Guide",
    "Fizban's Treasury of Dragons",
    "Monster Manual",
    "Mordenkainen Presents: Monsters of the Multiverse",
    "Player's Handbook",
    "Sword Coast Adventurer's Guide",
    "Tasha's Cauldron of Everything",
    "Waterdeep: Dragon Heist",
    "Waterdeep: Dungeon of the Mad Mage",
    "Xanathar's Guide to Everything",
]

races = [
    "Fizban's Treasury of Dragons",
    "Mordenkainen Presents: Monsters of the Multiverse",
    "Player's Handbook",
    "Sword Coast Adventurer's Guide",
    "Tasha's Cauldron of Everything",
    "Xanathar's Guide to Everything",
]

spells = [
    "Dungeon Master's Guide",
    "Player's Handbook",
    "Sword Coast Adventurer's Guide",
    "Tasha's Cauldron of Everything",
    "Xanathar's Guide to Everything",
]

overrides = [
    { name = "Silvery Barbs", allow = true },
    { name = "Expert Sidekick", allow = false },
    { name = "Spellcaster Sidekick", allow = false },
    { name = "Warrior Sidekick", allow = false },
    { name = "Githzerai", allow = false },
    { name = "Githyanki", allow = false },
    { name = "Harengon", allow = false },
    { name = "Shifter", allow = false },
    { name = "Changeling", allow = false },
    { name = "Custom Lineage", allow = false },
    { name = "Dragonborn", allow = false },
    { name = "Satyr", allow = false },
    { name = "Minotaur", allow = false },
]
